
name: GithHub Actions Demo
on: [push]
jobs:
  Test:
   runs-on: ubuntu latest
   steps:
     - run: echo "ðŸŒ» The job was successfully triggered by a ${{ github.event_name }} event" 
     - run: python main.py